version: '3.4'

services:
  serviciovalidaad_openshift:
    image: serviciovalidaadopenshift:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_serviciovalidaad_openshift$
    volumes:
      - C:\TFS\tfs.tisal.cl\Desarrollo Interno\Laboratorios\Cloud Native\ServicioValidaAD_OpenShift\ServicioValidaAD_OpenShift:/app
      - C:\Users\lpetruzzella\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_serviciovalidaad_openshift$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_serviciovalidaad_openshift$ bin/Debug/netcoreapp2.1/ServicioValidaAD_OpenShift.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
