version: '3.4'

services:
  lab-chat-angular:
    image: labchatangular:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_lab-chat-angular$
    volumes:
      - C:\TFS\tfs.tisal.cl\Desarrollo Interno\Laboratorios\Cloud Native\lab-chat-angular\lab-chat-angular:/app
      - C:\Users\lpetruzzella\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_lab-chat-angular$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_lab-chat-angular$ bin/Debug/netcoreapp2.1/lab-chat-angular.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
