version: '3.4'

services:
  lab-chat-angular:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44353
      - LOGIN_BASEURL=http://backend-login-api-lab-arquitectura-dev.appl.tisal.cl/
      - LOGIN_URLRELATIVA=api/v1/login/auth
    ports:
      - "56319:80"
      - "44353:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro